/**
 * Panel copy.
 *
 * Both dictionaries are bundled because the client bundle is a closed factory:
 * it may only `require` modules the module system already serves, so no runtime
 * import of a locale file is possible.
 *
 * `zh` is also the literal fallback for every key, so a missing dictionary
 * registration degrades to readable text instead of raw keys. Only keys the
 * panel actually uses belong here — an unused key is dead copy.
 */

/** Locale namespace registered with `ctx.locale`. */
export const NS = 'settings.pluginManager'

export const zh = {
  tab: '插件管理器',
  refresh: '重新讀取',
  reading: '讀取中…',
  search: '搜尋名稱、spec 或來源…',

  // The panel is three sections. Without a visible name on each, every row
  // reads as the same level and there is nowhere for the eye to land.
  sectionThirdParty: '非原裝插件',
  sectionEntries: '開機載入順序',
  sectionEnv: '環境',

  check: '檢查來源',
  checking: '檢查中…',
  checkScope: '唯讀，只比對本機檔案；不查 registry、不執行 git fetch',
  checkFailed: '檢查失敗',
  verdictCurrent: '未變動',
  verdictMoved: '有變動',
  verdictUnknown: '無法判斷',
  baselineLabel: '比對基準',

  selfTag: '本插件',
  // The card leads with exactly one of these. Only `stateNotRunning` means
  // something is wrong: enabled, declares a bundle, and still absent from the
  // boot graph. `stateLibrary` is the opposite — a normal, working outcome.
  stateRunning: '運行中',
  stateDisabled: '已停用',
  stateComputed: '狀態由運算式決定',
  stateNotRunning: '已啟用但未載入',
  // A profile dependency with no `dsh.bundle`. It is a library the other plugins
  // use, it never appears in the web boot graph, and that is correct — so it must
  // NOT borrow the words or the colour of a broken plugin.
  stateLibrary: '函式庫',
  stateUnknown: '狀態未知',
  stateNotBundle: '非 bundle',
  disabledBy: '停用來源',
  updateAvailable: '可更新',
  working: '處理中…',
  // The one sentence this feature may not omit. `disabled` is consumed when the
  // loader composes the tree, so a toggle is a file edit, not a live change —
  // reporting "done" without this would be the most misleading thing on the panel.
  restartRequired: '已寫入設定檔，重啟 dsh web 後生效。',
  writeRefused: '寫入被拒',

  sourceRegistry: 'registry',
  sourceLink: 'link（本地）',
  sourceFile: 'file（本機 tarball）',
  sourceTarballUrl: 'tarball URL',
  sourceGit: 'git',
  sourceAlias: 'npm: 別名',
  sourceWorkspace: 'workspace',
  sourceTagOrRange: 'tag／範圍',
  changeIntegrity: 'integrity',
  changeResolvedDir: 'resolvedDir',

  // ── 更新（變更管道）──────────────────────────────────────────────────────
  updatePanel: '更新',
  updateLoad: '載入版本',
  updateLoading: '載入中…',
  updateLocalOnly: '本機 .git 為準；不連網',
  updateAskRemote: '查遠端',
  updateAsking: '查詢中…',
  updateChecking: '檢查中…',
  updateCheck: '檢查更新',
  updateRefLabel: '目標版本／分支',
  updateApply: '更新',
  updateApplying: '更新中…',
  updateConfirm: '更新會先快照，失敗自動回滾。要繼續嗎？',
  updateGroupLocalVersions: '本機版本（tag）',
  updateGroupLocalBranches: '本機分支',
  updateGroupRemoteVersions: '遠端版本（tag）',
  updateGroupRemoteBranches: '遠端分支',
  updateCurrent: '目前',
  updateTypeTag: 'tag',
  updateTypeBranch: '分支',
  updateTypeRemote: '遠端',
  updateDetached: 'detached（不在任何分支上）',
  updateNewestTag: '最新 tag',
  updateNoRefs: '這個 checkout 讀不到任何 ref。',
  updateNoRemote: '這個 checkout 沒有 origin remote，所以只能選本機已有的 ref。',
  updateRemoteNotImplemented: '這個 host 還沒實作 ref 查詢（已驗證的只有 github.com）。',
  updateRemoteOk: '遠端已回覆',
  updateRemoteFailed: '遠端查詢失敗',
  updatePlan: '計畫',
  updatePlanNothing: '這台機器沒有可用的工具，所以計畫無法執行。',
  updateTools: '工具',
  updateToolGit: 'git',
  updateToolDsh: 'dsh',
  updateToolAbsent: '找不到',
  updateToolNotProbed: '未探測',
  updateWillRun: '將執行',
  updateNoChange: '已經在這個 ref 上，不需要更新。',
  updateRefused: '無法更新',
  updateDone: '已更新',
  updateRolledBack: '更新失敗，已回滾',
  updateRollbackFailed: '回滾也失敗了',
  updateSnapshotAt: '快照',
  updateResidue: '回滾殘留',
  updateSkippedVerify: '已略過裝前驗證',
  stepVerifyBefore: '裝前驗證',
  stepSnapshot: '快照',
  stepExecute: '執行',
  stepVerifyAfter: '裝後驗證',
  stepRollback: '回滾',
  statusPass: '通過',
  statusFail: '失敗',
  statusOk: '完成',
  statusSkipped: '略過',
  statusRestored: '已還原',
  updateRegistryNote: 'registry 來源的新版本只有查 registry 才知道；這裡做的是用原本的 spec 重新解析。',
  updateUrlNote: 'URL／tag 來源的 spec 永遠不變、內容會變，這裡做的是重新抓取。',
  updateRequiresGit: '移動本地 checkout 需要 git 執行檔，這台機器上找不到。',
  updateCloneHint: '替代做法：把來源改成 github:<owner>/<repo>#<ref>，再由官方 CLI 安裝。',
  updateInstallTitle: '安裝',
  updateCopy: '複製指令',
  updateInstallOpen: '開安裝說明',
  updateInstallManual: '面板不會替你安裝：這行指令要你自己貼進終端機，看過再跑。',

  installTitle: '安裝插件',
  installHint: '輸入套件名或 spec（例如 some-plugin、^1.2.0、github:owner/repo#v1.0.0）。先看計畫，再決定裝不裝。',
  installPlaceholder: '套件名或 spec',
  installPlan: '檢查計畫',
  installPlanning: '檢查中…',
  installRun: '安裝',
  installRunning: '安裝中…',
  installCommand: '會跑的指令',
  installToolDsh: 'dsh 啟動器',
  installToolReady: '找得到',
  installToolMissing: '找不到',
  installToolNotProbed: '沒探測（與「不可用」不同）',
  installFresh: '這顆目前不在 profile 裡——會是新增。',
  installReplaces: '這會改寫已記錄的 spec：',
  installSameSpec: 'profile 已經記著同一個 spec。重跑只會重新解析來源。',
  installNoName: '這個 spec 看不出會裝成什麼名字，所以面板無法比對它會不會取代已裝的插件。',
  installPipeline: '按下去會走完整管道：裝前驗證 → 快照 → 執行上面那行指令 → 再驗一次 → 失敗自動回滾。',
  installGoal: '裝之前驗、裝之前影、裝之後再驗、爆咗自動回滾。',
  installResultOk: '裝好了，而且裝後驗證通過。',
  installResultFailed: '失敗了，而且已經自動回滾。',
  installResultRollback: '回滾',
  installResultRestored: '已還原',
  installResultFresh: '沒有東西要還原',
  installResultRestart: '重啟 dsh web 之後才會載入。',
  installResultSpec: 'profile 現在記著',
  installRefused: '這個 spec 不被接受：',
  installByHand: '要裝它的話，用官方 CLI 自己貼：',

  at: '讀取時間',
  profile: 'profile',
  manifest: 'manifest',
  backendReady: '就緒',
  backendAbsent: '缺少',
  footnote: '版本讀自 node_modules 的 package.json；換版訊號指出哪個欄位才是「內容變了」的可靠依據。',

  emptySearchTitle: '沒有符合的插件',
  emptySearchBody: '換個關鍵字，或清掉搜尋看全部。',
  emptyClear: '清除搜尋',
  thirdPartyEmptyTitle: '沒有非原裝插件',
  thirdPartyEmptyBody: '這個 profile 只載入原裝 bundle。要新增就跑 dsh plugin add。',
  emptyDepsTitle: 'manifest 裡沒有 dependencies',
  emptyDepsBody: 'manifest 讀到了，但它沒有宣告任何依賴——所以沒有東西可以列。',

  warnTitle: '有插件沒載入',
  warnBody: '下列插件宣告了 web bundle，但沒有出現在目前的載入清單裡。',

  missingTitle: '讀不到 profile manifest',
  missingLead: '注意：這不等於「沒有插件」，而是「不知道」。面板讀不到 manifest，所以無法判斷安裝了什麼。',
  missingReason: '原因',
  missingTried: '嘗試過的位置',

  failed: '讀取失敗',
  badPayload: '宿主回傳了看不懂的資料形狀——面板無法呈現，但插件本身運作正常。',
  noHost: '宿主半沒有回應。',

  colIndex: '#',
  colId: 'entry id',
  colRev: 'rev',
  colMode: '載入',
  colInject: 'inject',
  colChangeSignal: '換版訊號',
  colSpec: 'spec',
  details: '詳細資訊',
  sourceLabel: '來源',
  modeImmediate: '立即',
  modeLazy: '按需',
  none: '—',
  entriesHidden: '全部 web entry（含原裝）',
  statThirdPartyLoaded: '已載入',

  // ── 認證來源 ──────────────────────────────────────────────────────────────
  // The section states one thing above the list: where a token may come from and
  // what the panel is allowed to know about it. Everything else is status.
  sectionCredentials: '認證來源',
  credSummaryNotNeeded: '目前不需要憑證——讀公開 repo 不需要，只有私有 repo 或 API 限流才要。',
  credSummarySet: '已設定憑證（面板只拿得到遮罩後綴）。',
  credIntro: '查遠端、更新私有 repo 需要 token。插件只問你自己提供的來源（面板輸入／插件 store／環境變數／gh），下面是實際狀態——面板只拿得到來源、可用性與遮罩後綴，拿不到 token 本身。需要認證的 git 操作另有代辦一途（預設關閉，可在設定開啟）。',
  credHost: '主機',
  credStore: 'store 檔',
  credStoreNone: 'store 裡沒有這個主機的 token',
  credMode: '檔案權限',
  credModeNone: '尚未建立',
  credModeOk: '0600 ✓',
  credModeBad: '⚠ 不是 0600',
  credOk: '可用',
  credNo: '不可用',
  credOff: '已停用',
  credToken: 'Token',
  credTokenHint: '貼上 token：只送到宿主半，存成 0600，不會回傳',
  credSave: '存進 store',
  credStoreFirst: '存進 store 之後，它就排在解析鏈第 2 位：後面的來源不會被問，而且更新時的 git 也會直接用它——不會再跳系統對話框。',
  credMethod: '認證方式',
  credMethodHint: '選一種方式，或讓插件照順序自己找。選定之後，其他來源就不會被問。',
  credMethodAuto: '自動（依序嘗試）',
  credMethodAutoHint: '依序問下面每一個來源，第一個有答案的勝出。',
  credMethodNotActive: '目前未選用',
  credHostStale: '⚠ 這個宿主半還是舊版（不認得 preferredSource），所以現在選了不會被記住——重啟 `dsh web` 之後才會生效。',
  credTokenShow: '顯示',
  credTokenHide: '隱藏',
  credTokenHelper: '貼上後按「存進 store」。存過之後，下面那些系統來源就不會被叫到。',
  credClearConfirm: '再按一次確認清除',
  credClear: '清除',
  credTest: '測試解析',
  credAdopt: '從其他來源匯入',
  credWorking: '處理中…',
  credDone: '完成',
  credResolved: '會用到的來源',
  credUnresolved: '目前沒有可用的 token',
  credSettings: '設定',
  credDefaultHost: '預設主機',
  credDisable: '停用來源（只在「自動」時有意義；停用的不會被問）',
  credSaveSettings: '儲存設定',
  credSavedSettings: '設定已儲存',
  credUseStoredToken: '更新時把 store 的 token 交給 git',
  credUseStoredTokenHelp: '本機 checkout 的 `git fetch`／`git merge` 會用你存在這裡的那個 token：寫成一個 0600 的暫存檔，只給那一個子行程讀，跑完就刪。git 的參數裡只會出現檔案路徑，不會出現 token。',
  credDelegateSourcetree: '讓 Sourcetree 代辦認證（借用它的憑證）',
  credDelegateSourcetreeHelp: '⚠ 開啟之後，「查遠端」會借用 Sourcetree 自己的 git 與它的 credential helper——那是你給 Sourcetree 的憑證，不是給這個插件的，所以預設關閉。憑證只交給那一個 git 子行程，本插件只看得到 ref 清單。',
}

export const en = {
  tab: 'Plugin Manager',
  refresh: 'Reload',
  reading: 'Reading…',
  search: 'Search name, spec or source…',

  sectionThirdParty: 'Third-party plugins',
  sectionEntries: 'Boot load order',
  sectionEnv: 'Environment',

  check: 'Check sources',
  checking: 'Checking…',
  checkScope: 'read-only, local files only; no registry query and no git fetch',
  checkFailed: 'Check failed',
  verdictCurrent: 'unchanged',
  verdictMoved: 'changed',
  verdictUnknown: 'unknown',
  baselineLabel: 'baseline',

  selfTag: 'this plugin',
  stateRunning: 'running',
  stateDisabled: 'disabled',
  stateComputed: 'state computed',
  stateNotRunning: 'enabled, not loaded',
  stateLibrary: 'library',
  stateUnknown: 'state unknown',
  stateNotBundle: 'not a bundle',
  disabledBy: 'disabled by',
  updateAvailable: 'update',
  working: 'Working…',
  restartRequired: 'Written to the config file. Takes effect after dsh web restarts.',
  writeRefused: 'Write refused',

  sourceRegistry: 'registry',
  sourceLink: 'link (local)',
  sourceFile: 'file (local tarball)',
  sourceTarballUrl: 'tarball URL',
  sourceGit: 'git',
  sourceAlias: 'npm: alias',
  sourceWorkspace: 'workspace',
  sourceTagOrRange: 'tag/range',
  changeIntegrity: 'integrity',
  changeResolvedDir: 'resolvedDir',

  // ── update (the change pipeline) ─────────────────────────────────────────
  updatePanel: 'Update',
  updateLoad: 'Load versions',
  updateLoading: 'Loading…',
  updateLocalOnly: 'from this machine’s .git only; no network',
  updateAskRemote: 'Ask remote',
  updateAsking: 'Asking…',
  updateChecking: 'Checking…',
  updateCheck: 'Check for updates',
  updateRefLabel: 'Target version / branch',
  updateApply: 'Update',
  updateApplying: 'Updating…',
  updateConfirm: 'An update snapshots first and rolls back automatically on failure. Continue?',
  updateGroupLocalVersions: 'local versions (tags)',
  updateGroupLocalBranches: 'local branches',
  updateGroupRemoteVersions: 'remote versions (tags)',
  updateGroupRemoteBranches: 'remote branches',
  updateCurrent: 'current',
  updateTypeTag: 'tag',
  updateTypeBranch: 'branch',
  updateTypeRemote: 'remote',
  updateDetached: 'detached (on no branch)',
  updateNewestTag: 'newest tag',
  updateNoRefs: 'No ref could be read from this checkout.',
  updateNoRemote: 'This checkout records no origin remote, so only the refs already on this machine can be chosen.',
  updateRemoteNotImplemented: 'No ref-listing API is implemented for this host (only github.com is verified).',
  updateRemoteOk: 'the remote answered',
  updateRemoteFailed: 'the remote could not be asked',
  updatePlan: 'Plan',
  updatePlanNothing: 'The tools this needs are not available on this machine, so the plan cannot run.',
  updateTools: 'Tools',
  updateToolGit: 'git',
  updateToolDsh: 'dsh',
  updateToolAbsent: 'not found',
  updateToolNotProbed: 'not probed',
  updateWillRun: 'Will run',
  updateNoChange: 'Already on this ref; nothing to update.',
  updateRefused: 'Cannot update',
  updateDone: 'Updated',
  updateRolledBack: 'The update failed and was rolled back',
  updateRollbackFailed: 'the rollback failed as well',
  updateSnapshotAt: 'snapshot',
  updateResidue: 'rollback residue',
  updateSkippedVerify: 'the pre-check was skipped',
  stepVerifyBefore: 'pre-check',
  stepSnapshot: 'snapshot',
  stepExecute: 'execute',
  stepVerifyAfter: 'post-check',
  stepRollback: 'rollback',
  statusPass: 'pass',
  statusFail: 'fail',
  statusOk: 'ok',
  statusSkipped: 'skipped',
  statusRestored: 'restored',
  updateRegistryNote: 'A newer registry version is only knowable by asking the registry; this re-resolves the recorded spec instead.',
  updateUrlNote: 'A URL or tag spec keeps its name while its content changes, so this refetches it.',
  updateRequiresGit: 'Moving a local checkout needs the git executable, and it is not on this machine.',
  updateCloneHint: 'Alternative: point the source at github:<owner>/<repo>#<ref> and let the official CLI install it.',
  updateInstallTitle: 'Install',
  updateCopy: 'Copy command',
  updateInstallOpen: 'How to install',
  updateInstallManual: 'This panel will not install it for you: paste the command into a terminal and read it before running it.',

  installTitle: 'Install a plugin',
  installHint: 'A package name or spec (for example some-plugin, ^1.2.0, github:owner/repo#v1.0.0). See the plan first, then decide.',
  installPlaceholder: 'package name or spec',
  installPlan: 'Check the plan',
  installPlanning: 'Checking…',
  installRun: 'Install',
  installRunning: 'Installing…',
  installCommand: 'The command this would run',
  installToolDsh: 'dsh launcher',
  installToolReady: 'found',
  installToolMissing: 'not found',
  installToolNotProbed: 'not probed (which is not the same as unavailable)',
  installFresh: 'This plugin is not in the profile yet — this would be an addition.',
  installReplaces: 'This REPLACES the recorded spec:',
  installSameSpec: 'The profile already records this exact spec. Re-running only re-resolves the source.',
  installNoName: 'This spec does not reveal the name it installs as, so the panel cannot tell whether it replaces an installed plugin.',
  installPipeline: 'Running it goes through the whole pipeline: verify → snapshot → the command above → verify again → automatic rollback on failure.',
  installGoal: 'Verified before, snapshotted before, verified after, rolled back automatically when it breaks.',
  installResultOk: 'Installed, and the post-install verification passed.',
  installResultFailed: 'It failed, and the profile was rolled back automatically.',
  installResultRollback: 'Rollback',
  installResultRestored: 'restored',
  installResultFresh: 'there was nothing to restore',
  installResultRestart: 'It loads after dsh web is restarted.',
  installResultSpec: 'The profile now records',
  installRefused: 'That spec is not accepted:',
  installByHand: 'To install it anyway, paste this into a terminal yourself:',

  at: 'read at',
  profile: 'profile',
  manifest: 'manifest',
  backendReady: 'ready',
  backendAbsent: 'absent',
  footnote: 'Version comes from the installed package.json; the change signal names the field that reliably shows a content change.',

  emptySearchTitle: 'No matching plugin',
  emptySearchBody: 'Try another keyword, or clear the search to see everything.',
  emptyClear: 'Clear search',
  thirdPartyEmptyTitle: 'No third-party plugin',
  thirdPartyEmptyBody: 'This profile loads shipped bundles only. Use dsh plugin add to install one.',
  emptyDepsTitle: 'The manifest declares no dependencies',
  emptyDepsBody: 'The manifest was read, but it declares no dependencies — so there is nothing to list.',

  warnTitle: 'A plugin did not load',
  warnBody: 'These plugins declare a web bundle but are absent from the current load list.',

  missingTitle: 'The profile manifest could not be read',
  missingLead: 'Note: this is not "no plugins", it is "unknown". The panel could not read the manifest, so it cannot tell what is installed.',
  missingReason: 'Reason',
  missingTried: 'Locations tried',

  failed: 'Read failed',
  badPayload: 'The host returned a payload shape this panel does not understand — nothing is broken, it just cannot render it.',
  noHost: 'The host half did not respond.',

  colIndex: '#',
  colId: 'entry id',
  colRev: 'rev',
  colMode: 'load',
  colInject: 'inject',
  colChangeSignal: 'change signal',
  colSpec: 'spec',
  details: 'Details',
  sourceLabel: 'source',
  modeImmediate: 'immediate',
  modeLazy: 'lazy',
  none: '—',
  entriesHidden: 'All web entries (shipped included)',
  statThirdPartyLoaded: 'loaded',

  sectionCredentials: 'Credentials',
  credSummaryNotNeeded: 'No credential is needed right now — reading a public repository needs none; only a private remote or the API rate limit does.',
  credSummarySet: 'A credential is stored (the panel only ever sees a masked hint).',
  credIntro: 'Fetching remotes and updating private repositories need a token. The plugin only asks sources you supplied yourself (panel input, this plugin’s own store, an environment variable, gh); this is what actually happens. The panel receives a source, its availability and a masked hint — never the token itself. Authenticated git operations have a separate delegated route, off by default.',
  credHost: 'host',
  credStore: 'store file',
  credStoreNone: 'no token for this host in the store',
  credMode: 'file mode',
  credModeNone: 'not created yet',
  credModeOk: '0600 ✓',
  credModeBad: '⚠ not 0600',
  credOk: 'ready',
  credNo: 'unavailable',
  credOff: 'disabled',
  credToken: 'Token',
  credTokenHint: 'Paste a token: it goes to the host half only, is stored 0600, and is never sent back',
  credSave: 'Save to store',
  credStoreFirst: 'Once a token is saved here it sits second in the chain: the later sources are not asked, and the git a checkout update runs uses it directly — no system dialog appears again.',
  credMethod: 'Credential method',
  credMethodHint: 'Pick one method, or let the plugin work down the list. Once chosen, the other sources are not asked.',
  credMethodAuto: 'Automatic (try in order)',
  credMethodAutoHint: 'ask each source below, in order, and take the first answer',
  credMethodNotActive: 'not selected',
  credHostStale: '⚠ This host half is older than this panel (it does not know preferredSource), so a choice would not be remembered yet — restart `dsh web` to make it stick.',
  credTokenShow: 'Show',
  credTokenHide: 'Hide',
  credTokenHelper: 'Paste, then save. Once stored, the system sources below are never called.',
  credClearConfirm: 'Press again to clear',
  credClear: 'Clear',
  credTest: 'Test resolution',
  credAdopt: 'Import from another source',
  credWorking: 'Working…',
  credDone: 'Done',
  credResolved: 'source that would answer',
  credUnresolved: 'none of the available sources has a token',
  credSettings: 'Settings',
  credDefaultHost: 'default host',
  credDisable: 'disabled sources (only meaningful under Automatic; a disabled source is never asked)',
  credSaveSettings: 'Save settings',
  credSavedSettings: 'Settings saved',
  credUseStoredToken: 'Hand this plugin’s stored token to git',
  credUseStoredTokenHelp: 'A local checkout’s `git fetch`/`git merge` uses the token you saved here: it is written to a 0600 temp file that only that one child reads, and deleted when the run ends. Only the file path appears in the git arguments — never the token.',
  credDelegateSourcetree: 'Let Sourcetree authenticate (borrows its credential)',
  credDelegateSourcetreeHelp: '⚠ When on, “check remote” BORROWS Sourcetree’s own git and its credential helper — that credential belongs to Sourcetree, not to this plugin, which is why this is off by default. It is handed to that one git child, and this plugin only ever sees the ref list.',
}
