/**
 * Panel copy.
 *
 * Both dictionaries are bundled because the client bundle is a closed factory:
 * it may only `require` modules the module system already serves, so no runtime
 * import of a locale file is possible.
 *
 * `zh` is also the literal fallback for every key, so a missing dictionary
 * registration degrades to readable text instead of raw keys. Only keys the
 * panel actually uses belong here — an unused key is dead copy.
 */

/** Locale namespace registered with `ctx.locale`. */
export const NS = 'settings.pluginManager'

export const zh = {
  tab: '插件管理器',
  refresh: '重新讀取',
  reading: '讀取中…',
  search: '搜尋名稱、spec 或來源…',

  // The panel is three sections. Without a visible name on each, every row
  // reads as the same level and there is nowhere for the eye to land.
  sectionThirdParty: '非原裝插件',
  sectionEntries: '開機載入順序',
  sectionEnv: '環境',

  check: '檢查來源',
  checking: '檢查中…',
  checkScope: '唯讀，只比對本機檔案；不查 registry、不執行 git fetch',
  checkFailed: '檢查失敗',
  verdictCurrent: '未變動',
  verdictMoved: '有變動',
  verdictUnknown: '無法判斷',
  baselineLabel: '比對基準',

  selfTag: '本插件',
  // The card leads with exactly one of these. Only `stateNotRunning` means
  // something is wrong: enabled, declares a bundle, and still absent from the
  // boot graph. `stateLibrary` is the opposite — a normal, working outcome.
  stateRunning: '運行中',
  stateDisabled: '已停用',
  stateComputed: '狀態由運算式決定',
  stateNotRunning: '已啟用但未載入',
  // A profile dependency with no `dsh.bundle`. It is a library the other plugins
  // use, it never appears in the web boot graph, and that is correct — so it must
  // NOT borrow the words or the colour of a broken plugin.
  stateLibrary: '函式庫',
  stateUnknown: '狀態未知',
  stateNotBundle: '非 bundle',
  disabledBy: '停用來源',
  updateAvailable: '可更新',
  working: '處理中…',
  // The one sentence this feature may not omit. `disabled` is consumed when the
  // loader composes the tree, so a toggle is a file edit, not a live change —
  // reporting "done" without this would be the most misleading thing on the panel.
  restartRequired: '已寫入設定檔，重啟 dsh web 後生效。',
  writeRefused: '寫入被拒',

  sourceRegistry: 'registry',
  sourceLink: 'link（本地）',
  sourceFile: 'file（本機 tarball）',
  sourceTarballUrl: 'tarball URL',
  sourceGit: 'git',
  sourceAlias: 'npm: 別名',
  sourceWorkspace: 'workspace',
  sourceTagOrRange: 'tag／範圍',
  changeIntegrity: 'integrity',
  changeResolvedDir: 'resolvedDir',

  // ── 更新（變更管道）──────────────────────────────────────────────────────
  updatePanel: '更新',
  updateLoad: '載入版本',
  updateLoading: '載入中…',
  updateLocalOnly: '本機 .git 為準；不連網',
  updateAskRemote: '查遠端',
  updateAsking: '查詢中…',
  updateChecking: '檢查中…',
  updateCheck: '檢查更新',
  updateRefLabel: '目標版本／分支',
  updateApply: '更新',
  updateApplying: '更新中…',
  updateConfirm: '更新會先快照，失敗自動回滾。要繼續嗎？',
  updateGroupLocalVersions: '本機版本（tag）',
  updateGroupLocalBranches: '本機分支',
  updateGroupRemoteVersions: '遠端版本（tag）',
  updateGroupRemoteBranches: '遠端分支',
  updateCurrent: '目前',
  updateDetached: 'detached（不在任何分支上）',
  updateNewestTag: '最新 tag',
  updateNoRefs: '這個 checkout 讀不到任何 ref。',
  updateNoRemote: '這個 checkout 沒有 origin remote，所以只能選本機已有的 ref。',
  updateRemoteNotImplemented: '這個 host 還沒實作 ref 查詢（已驗證的只有 github.com）。',
  updateRemoteOk: '遠端已回覆',
  updateRemoteFailed: '遠端查詢失敗',
  updatePlan: '計畫',
  updatePlanNothing: '這台機器沒有可用的工具，所以計畫無法執行。',
  updateTools: '工具',
  updateToolGit: 'git',
  updateToolDsh: 'dsh',
  updateToolAbsent: '找不到',
  updateWillRun: '將執行',
  updateNoChange: '已經在這個 ref 上，不需要更新。',
  updateRefused: '無法更新',
  updateDone: '已更新',
  updateRolledBack: '更新失敗，已回滾',
  updateRollbackFailed: '回滾也失敗了',
  updateSnapshotAt: '快照',
  updateResidue: '回滾殘留',
  updateSkippedVerify: '已略過裝前驗證',
  stepVerifyBefore: '裝前驗證',
  stepSnapshot: '快照',
  stepExecute: '執行',
  stepVerifyAfter: '裝後驗證',
  stepRollback: '回滾',
  statusPass: '通過',
  statusFail: '失敗',
  statusOk: '完成',
  statusSkipped: '略過',
  statusRestored: '已還原',
  updateRegistryNote: 'registry 來源的新版本只有查 registry 才知道；這裡做的是用原本的 spec 重新解析。',
  updateUrlNote: 'URL／tag 來源的 spec 永遠不變、內容會變，這裡做的是重新抓取。',
  updateRequiresGit: '移動本地 checkout 需要 git 執行檔，這台機器上找不到。',
  updateCloneHint: '替代做法：把來源改成 github:<owner>/<repo>#<ref>，再由官方 CLI 安裝。',

  at: '讀取時間',
  profile: 'profile',
  manifest: 'manifest',
  backendReady: '就緒',
  backendAbsent: '缺少',
  footnote: '版本讀自 node_modules 的 package.json；換版訊號指出哪個欄位才是「內容變了」的可靠依據。',

  emptySearchTitle: '沒有符合的插件',
  emptySearchBody: '換個關鍵字，或清掉搜尋看全部。',
  emptyClear: '清除搜尋',
  thirdPartyEmptyTitle: '沒有非原裝插件',
  thirdPartyEmptyBody: '這個 profile 只載入原裝 bundle。要新增就跑 dsh plugin add。',
  emptyDepsTitle: 'manifest 裡沒有 dependencies',
  emptyDepsBody: 'manifest 讀到了，但它沒有宣告任何依賴——所以沒有東西可以列。',

  warnTitle: '有插件沒載入',
  warnBody: '下列插件宣告了 web bundle，但沒有出現在目前的載入清單裡。',

  missingTitle: '讀不到 profile manifest',
  missingLead: '注意：這不等於「沒有插件」，而是「不知道」。面板讀不到 manifest，所以無法判斷安裝了什麼。',
  missingReason: '原因',
  missingTried: '嘗試過的位置',

  failed: '讀取失敗',
  badPayload: '宿主回傳了看不懂的資料形狀——面板無法呈現，但插件本身運作正常。',
  noHost: '宿主半沒有回應。',

  colIndex: '#',
  colId: 'entry id',
  colRev: 'rev',
  colMode: '載入',
  colInject: 'inject',
  colChangeSignal: '換版訊號',
  colSpec: 'spec',
  details: '詳細資訊',
  sourceLabel: '來源',
  modeImmediate: '立即',
  modeLazy: '按需',
  none: '—',
  entriesHidden: '全部 web entry（含原裝）',
  statThirdPartyLoaded: '已載入',
}

export const en = {
  tab: 'Plugin Manager',
  refresh: 'Reload',
  reading: 'Reading…',
  search: 'Search name, spec or source…',

  sectionThirdParty: 'Third-party plugins',
  sectionEntries: 'Boot load order',
  sectionEnv: 'Environment',

  check: 'Check sources',
  checking: 'Checking…',
  checkScope: 'read-only, local files only; no registry query and no git fetch',
  checkFailed: 'Check failed',
  verdictCurrent: 'unchanged',
  verdictMoved: 'changed',
  verdictUnknown: 'unknown',
  baselineLabel: 'baseline',

  selfTag: 'this plugin',
  stateRunning: 'running',
  stateDisabled: 'disabled',
  stateComputed: 'state computed',
  stateNotRunning: 'enabled, not loaded',
  stateLibrary: 'library',
  stateUnknown: 'state unknown',
  stateNotBundle: 'not a bundle',
  disabledBy: 'disabled by',
  updateAvailable: 'update',
  working: 'Working…',
  restartRequired: 'Written to the config file. Takes effect after dsh web restarts.',
  writeRefused: 'Write refused',

  sourceRegistry: 'registry',
  sourceLink: 'link (local)',
  sourceFile: 'file (local tarball)',
  sourceTarballUrl: 'tarball URL',
  sourceGit: 'git',
  sourceAlias: 'npm: alias',
  sourceWorkspace: 'workspace',
  sourceTagOrRange: 'tag/range',
  changeIntegrity: 'integrity',
  changeResolvedDir: 'resolvedDir',

  // ── update (the change pipeline) ─────────────────────────────────────────
  updatePanel: 'Update',
  updateLoad: 'Load versions',
  updateLoading: 'Loading…',
  updateLocalOnly: 'from this machine’s .git only; no network',
  updateAskRemote: 'Ask remote',
  updateAsking: 'Asking…',
  updateChecking: 'Checking…',
  updateCheck: 'Check for updates',
  updateRefLabel: 'Target version / branch',
  updateApply: 'Update',
  updateApplying: 'Updating…',
  updateConfirm: 'An update snapshots first and rolls back automatically on failure. Continue?',
  updateGroupLocalVersions: 'local versions (tags)',
  updateGroupLocalBranches: 'local branches',
  updateGroupRemoteVersions: 'remote versions (tags)',
  updateGroupRemoteBranches: 'remote branches',
  updateCurrent: 'current',
  updateDetached: 'detached (on no branch)',
  updateNewestTag: 'newest tag',
  updateNoRefs: 'No ref could be read from this checkout.',
  updateNoRemote: 'This checkout records no origin remote, so only the refs already on this machine can be chosen.',
  updateRemoteNotImplemented: 'No ref-listing API is implemented for this host (only github.com is verified).',
  updateRemoteOk: 'the remote answered',
  updateRemoteFailed: 'the remote could not be asked',
  updatePlan: 'Plan',
  updatePlanNothing: 'The tools this needs are not available on this machine, so the plan cannot run.',
  updateTools: 'Tools',
  updateToolGit: 'git',
  updateToolDsh: 'dsh',
  updateToolAbsent: 'not found',
  updateWillRun: 'Will run',
  updateNoChange: 'Already on this ref; nothing to update.',
  updateRefused: 'Cannot update',
  updateDone: 'Updated',
  updateRolledBack: 'The update failed and was rolled back',
  updateRollbackFailed: 'the rollback failed as well',
  updateSnapshotAt: 'snapshot',
  updateResidue: 'rollback residue',
  updateSkippedVerify: 'the pre-check was skipped',
  stepVerifyBefore: 'pre-check',
  stepSnapshot: 'snapshot',
  stepExecute: 'execute',
  stepVerifyAfter: 'post-check',
  stepRollback: 'rollback',
  statusPass: 'pass',
  statusFail: 'fail',
  statusOk: 'ok',
  statusSkipped: 'skipped',
  statusRestored: 'restored',
  updateRegistryNote: 'A newer registry version is only knowable by asking the registry; this re-resolves the recorded spec instead.',
  updateUrlNote: 'A URL or tag spec keeps its name while its content changes, so this refetches it.',
  updateRequiresGit: 'Moving a local checkout needs the git executable, and it is not on this machine.',
  updateCloneHint: 'Alternative: point the source at github:<owner>/<repo>#<ref> and let the official CLI install it.',

  at: 'read at',
  profile: 'profile',
  manifest: 'manifest',
  backendReady: 'ready',
  backendAbsent: 'absent',
  footnote: 'Version comes from the installed package.json; the change signal names the field that reliably shows a content change.',

  emptySearchTitle: 'No matching plugin',
  emptySearchBody: 'Try another keyword, or clear the search to see everything.',
  emptyClear: 'Clear search',
  thirdPartyEmptyTitle: 'No third-party plugin',
  thirdPartyEmptyBody: 'This profile loads shipped bundles only. Use dsh plugin add to install one.',
  emptyDepsTitle: 'The manifest declares no dependencies',
  emptyDepsBody: 'The manifest was read, but it declares no dependencies — so there is nothing to list.',

  warnTitle: 'A plugin did not load',
  warnBody: 'These plugins declare a web bundle but are absent from the current load list.',

  missingTitle: 'The profile manifest could not be read',
  missingLead: 'Note: this is not "no plugins", it is "unknown". The panel could not read the manifest, so it cannot tell what is installed.',
  missingReason: 'Reason',
  missingTried: 'Locations tried',

  failed: 'Read failed',
  badPayload: 'The host returned a payload shape this panel does not understand — nothing is broken, it just cannot render it.',
  noHost: 'The host half did not respond.',

  colIndex: '#',
  colId: 'entry id',
  colRev: 'rev',
  colMode: 'load',
  colInject: 'inject',
  colChangeSignal: 'change signal',
  colSpec: 'spec',
  details: 'Details',
  sourceLabel: 'source',
  modeImmediate: 'immediate',
  modeLazy: 'lazy',
  none: '—',
  entriesHidden: 'All web entries (shipped included)',
  statThirdPartyLoaded: 'loaded',
}
