/**
 * The panel component.
 *
 * Plain React, no JSX: the client bundle is generated by `build-client.mjs` and
 * served verbatim, so there is no transform step. `react` arrives as an argument
 * rather than through an import because the inlined modules have no require
 * graph at all — the bundle wrapper is the only place that calls `require`
 * (docs/host-notes.md F15).
 *
 * ## Structure
 *
 * The panel is three sections, each with a visible name:
 *
 *   1. 非原裝插件    the point of the tab — the cards you came to read
 *   2. 開機載入順序   collapsed diagnostic, closed by default
 *   3. 環境          provenance and status, the quietest text on the panel
 *
 * The first version emitted eight sibling `<div>`s with a border on each and
 * 11–14px text throughout. Nothing told the reader where one area ended and the
 * next began, which is exactly what came back: "everything looks like the same
 * level, I cannot find the transitions". Sections now carry a rule above
 * themselves plus a small uppercase name, and per-card diagnostics fold into a
 * disclosure so the cards stay scannable.
 */

/**
 * Build the panel component.
 * @param {object} react - the `react` seed module.
 * @param {(react: object) => object} makeUpdatePanel - the update-control factory,
 *   injected rather than imported: the inlined modules have no require graph, so
 *   every collaborator arrives as an argument (see build-client.mjs).
 * @returns {(props: object) => object} the panel component.
 */
export function createPanel(react, makeUpdatePanel) {
  const h = react.createElement
  const { useState, useEffect } = react
  const UpdatePanel = makeUpdatePanel(react).UpdatePanel

  /** Shorten a hash for display without lying about which one it is. */
  function short(value) {
    return typeof value === 'string' && value.length > 8 ? value.slice(0, 12) : value
  }

  /**
   * Localised label for a classified source.
   * @param {(key: string) => string} t - copy lookup.
   * @param {string} sourceType - the classification from the host.
   * @returns {string} display text.
   */
  function sourceLabel(t, sourceType) {
    const map = {
      registry: 'sourceRegistry',
      link: 'sourceLink',
      file: 'sourceFile',
      'tarball-url': 'sourceTarballUrl',
      git: 'sourceGit',
      alias: 'sourceAlias',
      workspace: 'sourceWorkspace',
      'tag-or-range': 'sourceTagOrRange',
    }
    const key = map[sourceType]
    return key === undefined ? String(sourceType) : t(key)
  }

  /** A titled section. The only component that draws a section transition. */
  function Section(props) {
    return h(
      'section',
      { className: 'pm-sec' },
      h('h4', { className: 'pm-sec-title' }, props.title),
      props.children,
    )
  }

  /** A key/value list rendered as a definition list, not as a wall of spans. */
  function Meta(props) {
    const rows = (Array.isArray(props.rows) ? props.rows : []).filter((row) => row !== null && row !== undefined)
    if (rows.length === 0) return null
    return h(
      'dl',
      { className: 'pm-meta' },
      rows.map((row) => [h('dt', { key: `t${row[0]}` }, row[0]), h('dd', { key: `d${row[0]}` }, row[1])]),
    )
  }

  /**
   * The single state a card leads with.
   *
   * Exactly one of four answers, and the four are not interchangeable:
   *
   *   running     enabled and present in the boot graph — the only good state
   *   disabled    a patch layer turned it off, and `disabledBy` names which
   *   not-running enabled, absent from the graph — a FAULT, not a choice
   *   computed    the flag is an expression, so it was never anyone's decision
   *
   * `enabledState` comes from the host; the fallback keeps an older payload
   * readable rather than blanking the row.
   * @param {object} plugin - one inventory row.
   * @returns {string} a copy key.
   */
  function stateKeyOf(plugin) {
    // A lookup table rather than a chain of `return 'stateX'` statements: the
    // copy audit finds keys by their `key: 'value'` shape, so a bare return
    // hides them and they get reported as dead while on screen. Same trap as
    // `verdictKeys` below.
    const stateKeys = {
      disabled: 'stateDisabled',
      computed: 'stateComputed',
      'not-loaded': 'stateNotRunning',
      library: 'stateLibrary',
      running: 'stateRunning',
      unknown: 'stateUnknown',
    }
    const state = typeof plugin.enabledState === 'string' ? plugin.enabledState : null
    if (state !== null && stateKeys[state] !== undefined) return stateKeys[state]
    // No state from the host: fall back to what the graph alone can say.
    return plugin.loaded === true ? 'stateRunning' : 'stateUnknown'
  }

  /**
   * The class for one card, given its plugin row.
   *
   * Exported for the render test through `createPanel`. The class cannot be
   * asserted from the descriptor tree: `h(PluginCard, …)` is a COMPONENT
   * descriptor, so `className` only exists after React invokes the component —
   * which the test stub deliberately never does. A test that looked for
   * `pm-card-off` in the tree found nothing and reported a styling bug that was
   * not there (docs/host-notes.md F23, the same trap as `pm-card`).
   * @param {object} plugin - one inventory row.
   * @returns {string} the className.
   */
  function cardClassOf(plugin) {
    // Read the state STRING, not only the boolean: a payload can carry the state
    // without the boolean, and `enabled === false` alone would then render a
    // disabled plugin as if nothing were wrong. The fault case matters too —
    // enabled but absent from the graph is not "off", it is broken, and it gets
    // the same attention colour without claiming the user turned it off.
    if (plugin.enabled === false || plugin.enabledState === 'disabled' || plugin.enabledState === 'not-loaded') {
      return 'pm-card pm-card-off'
    }
    return plugin.self === true ? 'pm-card pm-card-self' : 'pm-card'
  }

  /**
   * The version chip: `package.json`'s version, always.
   *
   * I first made this source-dependent — a commit for a local checkout, a version
   * for a registry install — on the theory that a checkout's version field must be
   * stale. That theory was wrong, and measurably so: `dsh-power` declares `1.8.0`
   * and `dsh-tavern` declares `2.6.72`, and neither repo carries a single git tag,
   * so both are maintained by hand. I had generalised from my own package (which
   * really did still say `0.0.0`) to every checkout.
   *
   * `v0.2.1` is also the format a reader already knows, and one signal everywhere
   * beats two signals that need a rule to tell apart.
   *
   * @param {object} plugin - one inventory row.
   * @returns {object|null} the chip element, or null when there is no version.
   */
  function versionChipFor(plugin) {
    if (plugin.version === null || plugin.version === undefined) return null
    return h('span', { className: 'pm-ver' }, `v${plugin.version}`)
  }

  /** One installed-plugin card. */
  function PluginCard(props) {
    const plugin = props.plugin
    const t = props.t

    const spec = specIsInformative(plugin) ? plugin.spec : null

    // The detection result for this plugin, once a check has been run. Absent
    // until then, and the card then makes no claim about freshness at all —
    // which is the correct default, not a missing feature.
    const detect = props.detect === null || props.detect === undefined ? null : props.detect
    // A lookup table, not an inline ternary: `test/copy.test.mjs` finds keys by
    // scanning for the `verdictX: '…'` shape, so a ternary hides them from the
    // dead-key check — which is exactly how `verdictCurrent` was reported unused
    // while it was on screen.
    const verdictKeys = { current: 'verdictCurrent', moved: 'verdictMoved', unknown: 'verdictUnknown' }
    const verdictKey = detect === null ? null : (verdictKeys[detect.verdict] ?? 'verdictUnknown')

    const stateKey = stateKeyOf(plugin)
    const disabled = plugin.enabled === false || plugin.enabledState === 'disabled'
    const faulted = plugin.enabledState === 'not-loaded'
    // A library is not a fault and must not be coloured like one: it has no
    // bundle to load, so its absence from the boot graph is the normal case.
    const isLibrary = plugin.enabledState === 'library'
    // The switch's own state. `enabled === null` (a computed flag) leaves it off,
    // because a switch may only claim a state somebody can act on — the label
    // next to it carries the real answer.
    const enabledNow = plugin.enabled !== false && plugin.enabledState !== 'disabled'
    // The state, as plain text beside the switch. Not a chip: the switch already
    // carries the colour, so a second coloured pill is two signals for one fact —
    // and plain text is what lets the right edge line up (rule: color-not-only is
    // satisfied by the LABEL, so the switch does not have to be the only cue).
    const stateClass =
      disabled || faulted
        ? 'pm-state pm-state-off'
        : plugin.loaded === true
          ? 'pm-state pm-state-on'
          : 'pm-state'
    const stateLabel = h('span', { className: stateClass }, t(stateKey))

    const updateChip =
      detect !== null && detect.verdict === 'moved'
        ? h('span', { className: 'pm-chip pm-chip-off' }, t('updateAvailable'))
        : null

    return h(
      'article',
      { className: cardClassOf(plugin) },
      // ONE row, two columns: identity takes the free space, the control and its
      // state are pinned right. There is deliberately NO fixed width — the status
      // used to sit right after the name, so it moved with the name's length and
      // the list looked ragged. A grid column solves that without a magic number,
      // and without breaking when a Chinese label and an English one differ in
      // width by a third.
      h(
        'div',
        { className: 'pm-row' },
        h(
          'span',
          { className: 'pm-lead' },
          h('span', { className: 'pm-name' }, plugin.name),
          // Which version signal is shown depends on WHERE the plugin came from,
          // and getting this wrong makes the card lie.
          //
          // For a registry package the spec resolves to a real version, so
          // `package.json` is the answer. For a local checkout it is not: this
          // very plugin declares `0.0.0` from its first scaffold and has been
          // edited many times since, so the version field is technically accurate
          // and practically meaningless. The commit is the identity there, and
          // `detect.commit` is already read from `.git` before any check runs —
          // it does not depend on pressing the button.
          versionChipFor(plugin),
          // A verdict is an event, not a status, so it stays beside the identity
          // rather than in the status zone.
          updateChip,
        ),
        // The action, and the state it acts on. The label is also the only place
        // the restart requirement is discoverable without reading the notice.
        h(
          'button',
          {
            type: 'button',
            className: props.busy === true ? 'pm-switch pm-switch-busy' : enabledNow ? 'pm-switch pm-switch-on' : 'pm-switch',
            role: 'switch',
            'aria-checked': enabledNow ? 'true' : 'false',
            'aria-label': `${plugin.name} — ${t(stateKey)}`,
            disabled: props.busy === true || props.canToggle !== true,
            title: props.canToggle === true ? t('restartRequired') : t('writeRefused'),
            onClick: () => props.onToggle(plugin.name, plugin.enabled === false),
          },
          h('span', { className: 'pm-switch-knob' }),
        ),
        props.busy === true ? h('span', { className: 'pm-state' }, t('working')) : stateLabel,
      ),
      h(
        'details',
        { className: 'pm-disclosure' },
        // The summary names what is INSIDE ("details"), not one of the things
        // inside it. It read `換版` — "change signal" — which describes a single
        // field of the fold and gives no reason to open it.
        h('summary', null, detect === null ? t('details') : `${t('details')} · ${t(verdictKey)}`),
        h(Meta, {
          rows: [
            spec === null ? null : [t('colSpec'), h('span', { className: 'pm-mono pm-break' }, spec)],
            [t('colChangeSignal'), plugin.changeSignal === 'resolvedDir' ? t('changeResolvedDir') : t('changeIntegrity')],
            // Which layer disabled it. Folded, because the state chip already
            // says THAT it is off; this says BY WHAT, which is a lookup.
            disabled === true || faulted === true
              ? [
                  t('disabledBy'),
                  h(
                    'span',
                    { className: 'pm-break' },
                    plugin.disabledBy === null || plugin.disabledBy === undefined ? t(stateKey) : String(plugin.disabledBy),
                  ),
                ]
              : null,
            // Secondary identity: only meaningful for the plugins they apply to,
            // and never worth a chip in the row above.
            plugin.sourceType === undefined || plugin.sourceType === null
              ? null
              : [t('sourceLabel'), sourceLabel(t, plugin.sourceType)],
            // These two rows used to render their own LABEL as the VALUE
            // ("本插件: 本插件"), which is a tautology the reader learns nothing
            // from. The left column is a label, so the right column has to carry
            // an actual answer, or the row should not exist.
            plugin.self === true ? [t('selfTag'), plugin.resolvedDir === null ? t('none') : plugin.resolvedDir] : null,
            plugin.declaresBundle === false ? [t('stateNotBundle'), t('stateLibrary')] : null,
            plugin.enabledReason === null || plugin.enabledReason === undefined
              ? null
              : [t(stateKey), h('span', { className: 'pm-break' }, String(plugin.enabledReason))],
            // Only present once a check has run. Until then the card makes no
            // claim about freshness at all.
            detect === null ? null : [t('baselineLabel'), h('span', { className: 'pm-break' }, String(detect.baseline ?? t('none')))],
            detect === null ? null : [t(verdictKey), h('span', { className: 'pm-break' }, String(detect.verdictReason))],
            // The commit is no longer the VERSION (see `versionChipFor`), but it is
            // still what identifies which build is running — the question a
            // developer editing a local checkout actually asks. Read from the
            // overview, so it is here without pressing anything; the detection row
            // is only a fallback for a payload from an older host half.
            commitOf(plugin, detect) === null ? null : ['commit', h('span', { className: 'pm-mono' }, commitOf(plugin, detect))],
            detect === null || detect.dirHash === null
              ? null
              : [
                  'fingerprint',
                  h(
                    'span',
                    { className: 'pm-mono' },
                    `${detect.dirHash} · ${detect.fileCount ?? '?'} files${detect.dirHashTruncated === true ? ' (truncated)' : ''}`,
                  ),
                ],
          ],
        }),
      ),
      // The update control lives at the BOTTOM of the fold, after the diagnosis.
      // Reading order is the argument: "what is this, where did it come from,
      // what does the machine know about it" comes before "change it". It is
      // inside the disclosure rather than in the row so the list stays scannable
      // — see update.js for why that trade was made.
      h(UpdatePanel, {
        t,
        plugin,
        face: props.face ?? null,
        busy: props.busy === true,
        onChanged: props.onWrite,
      }),
    )
  }

  /**
   * The commit a plugin is running, when it can be determined.
   *
   * Prefers the overview's value, which the host resolves by reading `.git` — so
   * it is present before any check — and falls back to the detection row for a
   * payload from an older host half.
   *
   * @param {object} plugin - one inventory row.
   * @param {object|null} detect - that plugin's detection row, when one exists.
   * @returns {string|null} the full commit, or null.
   */
  function commitOf(plugin, detect) {
    if (plugin.gitCommit !== null && plugin.gitCommit !== undefined) return String(plugin.gitCommit)
    if (detect === null || detect.commit === null || detect.commit === undefined) return null
    return String(detect.commit)
  }

  /**
   * Whether a plugin's spec carries information beyond its version.
   * @param {object} plugin - one inventory row.
   * @returns {boolean} true when the spec should render.
   */
  function specIsInformative(plugin) {    if (typeof plugin.spec !== 'string' || plugin.spec.length === 0) return false
    if (plugin.version !== null && plugin.spec === plugin.version) return false
    // A caret/tilde range that resolves to the version on screen is noise too.
    if (plugin.version !== null && plugin.spec.replace(/^[\^~]/, '') === plugin.version) return false
    return true
  }

  /** One boot-graph entry row (secondary, folded away). */
  function EntryRow(props) {
    const row = props.row
    const t = props.t
    // `inject` is the one entry field a hand-built or older payload may omit.
    const inject = Array.isArray(row.inject) ? row.inject : []
    return h(
      'tr',
      { className: row.self ? 'pm-row-self' : undefined },
      h('td', { className: 'pm-mono pm-dim' }, String(row.index)),
      h('td', null, h('span', { className: 'pm-name' }, row.id)),
      h('td', { className: 'pm-mono pm-dim' }, row.rev === null ? t('none') : short(row.rev)),
      h('td', { className: 'pm-dim' }, row.immediate ? t('modeImmediate') : t('modeLazy')),
      h('td', { className: 'pm-mono pm-dim pm-break' }, inject.length === 0 ? t('none') : inject.join(', ')),
    )
  }

  /** A callout. Earns its box; an empty state deliberately does not get one. */
  function Notice(props) {
    return h(
      'div',
      { className: props.bad === true ? 'pm-note pm-note-bad' : 'pm-note' },
      h('div', { className: 'pm-note-title' }, props.title),
      props.body === null || props.body === undefined ? null : h('div', { className: 'pm-note-body' }, props.body),
      props.children,
    )
  }

  /** A centred empty state with at most one action. */
  function Empty(props) {
    return h(
      'div',
      { className: 'pm-empty' },
      h('div', { className: 'pm-empty-icon' }, '○'),
      h('div', { className: 'pm-empty-title' }, props.title),
      props.body === null || props.body === undefined ? null : h('div', { className: 'pm-empty-body' }, props.body),
      props.action === null || props.action === undefined ? null : props.action,
    )
  }

  /**
   * Attached for tests. `PluginCard` and its two rules cannot be observed from
   * the descriptor tree: `h(PluginCard, …)` is a component descriptor and the
   * test stub deliberately never invokes components, so the class name, the
   * state key and the card's row count only exist after React would have called
   * it. Exposing the units keeps the assertions honest instead of weakening
   * them to whatever the tree happens to show. Not public surface — nothing in
   * the bundle reads these.
   */
  Panel.__cardClassOf = cardClassOf
  Panel.__stateKeyOf = stateKeyOf
  Panel.__PluginCard = PluginCard

  return Panel
  function Panel(props) {
    const t = props.t
    const [tick, setTick] = useState(0)
    const [query, setQuery] = useState('')
    const [state, setState] = useState({ phase: 'loading', data: null, error: null })
    // Detection is a separate, on-demand read: it fingerprints linked plugin
    // trees, which is real work the tab must not do just for being opened (R4).
    // Hook order is load-bearing for the test stub: see renderPanel's `__seed`.
    const [detect, setDetect] = useState({ phase: 'idle', report: null, error: null })
    // Toggle bookkeeping. `writing` holds the id currently being written so only
    // that card shows "working", and `outcome` holds the last write result.
    const [writing, setWriting] = useState(null)
    const [outcome, setOutcome] = useState(null)

    /**
     * Set one plugin's enabled state.
     *
     * On success the panel reloads, because the state shown must come from the
     * host rather than from an assumption about what the write did. On refusal
     * the reason is displayed as-is: a sandbox denial is an answer.
     * @param {string} id - the loader row id.
     * @param {boolean} enabled - the desired state.
     */
    function runToggle(id, enabled) {
      if (props.face === null || props.face === undefined || typeof props.face.setEnabled !== 'function') {
        setOutcome({ ok: false, id, error: t('noHost'), restartRequired: false })
        return
      }
      setWriting(id)
      setOutcome(null)
      props.face
        .setEnabled(id, enabled)
        .then((result) => {
          setWriting(null)
          setOutcome({ ...result, id })
          if (result !== null && result !== undefined && result.ok === true) setTick((n) => n + 1)
        })
        .catch((error) => {
          setWriting(null)
          setOutcome({ ok: false, id, error: error && error.message ? error.message : String(error), restartRequired: false })
        })
    }

    /** Run one detection pass. Read-only on the host side by construction. */
    function runDetect() {
      if (props.face === null || props.face === undefined || typeof props.face.detect !== 'function') {
        setDetect({ phase: 'error', report: null, error: t('noHost') })
        return
      }
      setDetect({ phase: 'checking', report: null, error: null })
      props.face
        .detect()
        .then((report) => setDetect({ phase: 'ready', report, error: null }))
        .catch((error) => {
          setDetect({ phase: 'error', report: null, error: error && error.message ? error.message : String(error) })
        })
    }

    useEffect(() => {      let alive = true

      // No face means the page had no usable fetch; say so instead of throwing,
      // so the tab still renders and the reason is visible.
      if (props.face === null || props.face === undefined) {
        setState({ phase: 'error', data: null, error: t('noHost') })
        return () => {
          alive = false
        }
      }

      setState((prev) => ({ phase: 'loading', data: prev.data, error: null }))
      props.face
        .load()
        .then((data) => {
          if (alive) setState({ phase: 'ready', data, error: null })
        })
        .catch((error) => {
          if (alive) {
            setState({ phase: 'error', data: null, error: error && error.message ? error.message : String(error) })
          }
        })
      return () => {
        alive = false
      }
    }, [tick])

    const data = state.data
    // Every section reads through a guard: one absent field must degrade to a
    // missing row, never blank the whole panel. A single unguarded read of an
    // optional field is what broke this panel once (`data.backend`, which the
    // overview endpoint does not serve on its own).
    const absent = data === null || data === undefined
    const plugins = absent || !Array.isArray(data.thirdParty) ? [] : data.thirdParty
    const entries = absent || !Array.isArray(data.entries) ? [] : data.entries
    const notices = absent || !Array.isArray(data.notices) ? [] : data.notices
    const meta = absent ? null : data.pluginInventory
    const backend = absent ? null : data.backend

    // A payload shape this renderer does not understand must say so rather than
    // throw: an exception inside a slot entry blanks the tab and logs a stack,
    // which hides the actual reason.
    if (state.phase === 'ready' && (absent || typeof data !== 'object')) {
      return h('div', { className: 'pm-root' }, h(Notice, { bad: true, title: t('badPayload') }))
    }

    const needle = query.trim().toLowerCase()
    const shown =
      needle.length === 0
        ? plugins
        : plugins.filter(
            (plugin) =>
              String(plugin.name).toLowerCase().includes(needle) ||
              String(plugin.spec ?? '').toLowerCase().includes(needle) ||
              sourceLabel(t, plugin.sourceType).toLowerCase().includes(needle),
          )

    const loadedCount = plugins.filter((plugin) => plugin.loaded === true).length
    const unresolved = meta !== null && meta.available !== true
    const searching = needle.length > 0

    // A plugin that declares a bundle yet is absent from the live load list is
    // the one condition worth shouting about: an installed plugin is not running.
    const stragglers = plugins.filter((plugin) => plugin.declaresBundle === true && plugin.loaded !== true)

    const header = h(
      'div',
      { className: 'pm-head' },
      h('div', { className: 'pm-h1' }, h('h3', { className: 'pm-title' }, t('tab')), h('span', { className: 'pm-count' }, String(plugins.length))),
    )

    // ── section 1: the plugins ──────────────────────────────────────────────
    // The input carries a real <label>, not just a placeholder: a placeholder
    // vanishes the moment you type, which leaves no visible name for the field.
    const controls = h(
      'div',
      { className: 'pm-controls' },
      h('label', { className: 'pm-sr', htmlFor: 'pm-search' }, t('search')),
      h('input', {
        id: 'pm-search',
        type: 'search',
        className: 'pm-input',
        placeholder: t('search'),
        value: query,
        onChange: (event) => setQuery(event.target && typeof event.target.value === 'string' ? event.target.value : ''),
      }),
      searching ? h('span', { className: 'pm-right' }, `${shown.length} / ${plugins.length}`) : null,
      h(
        'button',
        {
          type: 'button',
          className: 'pm-btn',
          // Detection is the only action here that reads plugin internals, so it
          // says what it will and will not do right next to the button. A check
          // that might touch the network is a check people hesitate to press.
          title: t('checkScope'),
          disabled: detect.phase === 'checking' || state.phase !== 'ready' || unresolved,
          onClick: () => runDetect(),
        },
        detect.phase === 'checking' ? t('checking') : t('check'),
      ),
      h(
        'button',
        {
          type: 'button',
          className: 'pm-btn',
          disabled: state.phase === 'loading',
          onClick: () => setTick((n) => n + 1),
        },
        state.phase === 'loading' ? t('reading') : t('refresh'),
      ),
    )

    // Name-keyed so a card can find its own verdict. Built once per render rather
    // than scanned per card, which would be quadratic on a long plugin list.
    const report = detect.phase === 'ready' && detect.report !== null ? detect.report : null
    const verdicts = new Map()
    if (report !== null && Array.isArray(report.plugins)) {
      for (const row of report.plugins) {
        if (row !== null && typeof row === 'object' && typeof row.name === 'string') verdicts.set(row.name, row)
      }
    }

    const clearAction = h(
      'button',
      { type: 'button', className: 'pm-btn', onClick: () => setQuery('') },
      t('emptyClear'),
    )

    // The unreadable-manifest branch is the one place the panel must refuse to
    // answer: "cannot read" is not "nothing installed", and conflating the two
    // is the failure this whole feature exists to avoid.
    const tried = notices.filter((text) => text.indexOf('→') !== -1)
    const inventory = unresolved
      ? h(
          Notice,
          { bad: true, title: t('missingTitle'), body: t('missingLead') },
          h(
            'div',
            { className: 'pm-note-body' },
            `${t('missingReason')}：${meta.reason === null || meta.reason === undefined ? t('none') : meta.reason}`,
          ),
          tried.length === 0
            ? null
            : h(
                'div',
                null,
                h('div', { className: 'pm-note-body' }, t('missingTried')),
                h('ul', { className: 'pm-tried' }, tried.map((text, index) => h('li', { key: `a${index}` }, text))),
              ),
        )
      : shown.length === 0
        ? searching
          ? h(Empty, { title: t('emptySearchTitle'), body: t('emptySearchBody'), action: clearAction })
          : h(Empty, {
              title: meta !== null && meta.available === true ? t('emptyDepsTitle') : t('thirdPartyEmptyTitle'),
              body: meta !== null && meta.available === true ? t('emptyDepsBody') : t('thirdPartyEmptyBody'),
            })
        : h(
            'div',
            { className: 'pm-list' },
            shown.map((plugin) =>
              h(PluginCard, {
                key: plugin.name,
                plugin,
                t,
                detect: verdicts.get(plugin.name) ?? null,
                busy: writing === plugin.name,
                // A write is only worth attempting once the profile has been read.
                canToggle: unresolved === false && typeof props.face?.setEnabled === 'function',
                onToggle: runToggle,
                // The host face AND a way to re-read the list: an update changes
                // the spec, the version and the commit, so the panel must reload
                // from the host rather than re-render its own stale copy.
                face: props.face ?? null,
                onWrite: () => setTick((n) => n + 1),
              }),
            ),
          )

    // ── section 2: boot order (diagnostic, folded) ──────────────────────────
    const entryTable =
      state.phase !== 'ready' || entries.length === 0
        ? null
        : h(
            'details',
            { className: 'pm-disclosure' },
            h('summary', null, `${t('entriesHidden')} · ${entries.length}`),
            h(
              'table',
              { className: 'pm-table' },
              h(
                'thead',
                null,
                h(
                  'tr',
                  null,
                  h('th', { className: 'pm-w-idx' }, t('colIndex')),
                  h('th', null, t('colId')),
                  h('th', { className: 'pm-w-rev' }, t('colRev')),
                  h('th', { className: 'pm-w-mode' }, t('colMode')),
                  h('th', null, t('colInject')),
                ),
              ),
              h('tbody', null, entries.map((row) => h(EntryRow, { key: `${row.id}#${row.index}`, row, t }))),
            ),
          )

    // ── section 3: environment (quietest) ───────────────────────────────────
    const envRows = []
    if (meta !== null && meta.profile !== null && meta.profile !== undefined) {
      envRows.push([t('profile'), `${meta.profile.name} · ${meta.profile.source}`])
    }
    if (meta !== null && meta.manifestPath !== null && meta.manifestPath !== undefined) {
      envRows.push([t('manifest'), h('span', { className: 'pm-mono pm-break' }, meta.manifestPath)])
    }
    if (backend !== null && backend !== undefined) {
      envRows.push([
        'backend',
        `fs=${backend.fs === 'ready' ? t('backendReady') : t('backendAbsent')} · clientModules=${backend.clientModules === 'ready' ? t('backendReady') : t('backendAbsent')}`,
      ])
    }

    const foot =
      state.phase !== 'ready' || absent
        ? null
        : h(
            'footer',
            { className: 'pm-foot' },
            h(
              'span',
              null,
              `${t('at')}：${new Date(data.at).toLocaleTimeString()} · ${t('statThirdPartyLoaded')} ${loadedCount} / ${plugins.length}`,
            ),
            h('span', { className: 'pm-foot-note' }, t('footnote')),
          )

    return h(
      'div',
      { className: 'pm-root' },
      header,

      h(
        Section,
        { title: t('sectionThirdParty') },
        stragglers.length === 0 ? null : h(Notice, { title: t('warnTitle'), body: t('warnBody') }),
        state.phase === 'error' ? h(Notice, { bad: true, title: t('failed'), body: String(state.error) }) : null,
        // A failed check must say so where the button is. Without this the
        // button simply stops saying "checking" and nothing changes on screen,
        // which reads as "no news" rather than "the check did not run".
        detect.phase === 'error' ? h(Notice, { bad: true, title: t('checkFailed'), body: String(detect.error) }) : null,
        // The write outcome. A success states the restart in the same breath as
        // the success — that pairing is the whole point, and separating them
        // would let "done" be read as "in effect".
        //
        // The title names the RESULTING state, not the action that was taken:
        // `toggleOn`/`toggleOff` are verbs ("enable"/"disable"), so using them
        // here read as "already enabled" when the switch had just been turned
        // off. The state words are the same ones the card shows.
        outcome === null
          ? null
          : outcome.ok === true
            ? h(Notice, {
                title: `${outcome.id} → ${outcome.enabled === false ? t('stateDisabled') : t('stateRunning')}`,
                body: outcome.restartRequired === true ? t('restartRequired') : (outcome.restartNote ?? null),
              })
            : h(Notice, {
                bad: true,
                title: outcome.denied === true ? t('writeRefused') : t('checkFailed'),
                body: String(outcome.error ?? ''),
              }),
        unresolved ? null : controls,
        inventory,
      ),

      entryTable === null ? null : h(Section, { title: t('sectionEntries') }, entryTable),

      envRows.length === 0 ? null : h(Section, { title: t('sectionEnv') }, h(Meta, { rows: envRows })),

      foot,
    )
  }
}
